/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package currencyconverter;

import javax.swing.JOptionPane;

/**
 *
 * @author Nichi
 */
public class Currency extends javax.swing.JFrame {

    /**
     * Creates new form Currency
     */
    public Currency() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        txtfrom = new javax.swing.JComboBox<>();
        txtto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Enter the Amount");

        jLabel2.setText("From");

        jLabel3.setText("To");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR", "USD", "LEI", "GBP" }));

        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EUR", "USD", "LEI", "GBP" }));

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reverse");
        jButton2.setMaximumSize(new java.awt.Dimension(587, 521));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtfrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtto, 0, 137, Short.MAX_VALUE)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Double total;
        try{
           Double amount=Double.parseDouble(txtAmount.getText());    
        
 
        
        if(txtfrom.getSelectedItem().toString()=="USD" && txtto.getSelectedItem().toString() =="EUR"){
            total=amount*0.83;
            JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());
        }
        else
            if(txtfrom.getSelectedItem().toString()=="EUR" && txtto.getSelectedItem().toString() =="USD"){
                total=amount*1.21;
                 JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());
            }
            else if(txtfrom.getSelectedItem().toString()=="USD" && txtto.getSelectedItem().toString() =="LEI"){
                   total=amount*4.07;
                 JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());
            } 
            else if(txtfrom.getSelectedItem().toString()=="LEI" && txtto.getSelectedItem().toString() =="USD"){
                total=amount*0.25;
                JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());
            } 
            else if(txtfrom.getSelectedItem().toString()=="USD" && txtto.getSelectedItem().toString() =="GBP"){
                total=amount*0.72;
                JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
            else if(txtfrom.getSelectedItem().toString()=="GBP" && txtto.getSelectedItem().toString() =="USD"){
                total=amount*1.39;
                 JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());
      
            }
            else if(txtfrom.getSelectedItem().toString()=="USD" && txtto.getSelectedItem().toString() =="USD"){
                total=amount;
                                 JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
            else if(txtfrom.getSelectedItem().toString()=="EUR" && txtto.getSelectedItem().toString() =="LEI"){
                total=amount*4.92;                 
                JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
            else if(txtfrom.getSelectedItem().toString()=="LEI" && txtto.getSelectedItem().toString() =="EUR"){
               total= amount*0.20; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        else if(txtfrom.getSelectedItem().toString()=="EUR" && txtto.getSelectedItem().toString() =="GBP"){
               total= amount*0.87; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        
        else if(txtfrom.getSelectedItem().toString()=="GBP" && txtto.getSelectedItem().toString() =="EUR"){
               total= amount*1.15; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        
        else if(txtfrom.getSelectedItem().toString()=="EUR" && txtto.getSelectedItem().toString() =="EUR"){
               total= amount; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        else if(txtfrom.getSelectedItem().toString()=="LEI" && txtto.getSelectedItem().toString() =="LEI"){
               total= amount; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        
        else if(txtfrom.getSelectedItem().toString()=="LEI" && txtto.getSelectedItem().toString() =="GBP"){
               total= amount*0.18; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        else if(txtfrom.getSelectedItem().toString()=="GBP" && txtto.getSelectedItem().toString() =="LEI"){
               total= amount*5.64; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        
        else if(txtfrom.getSelectedItem().toString()=="GBP" && txtto.getSelectedItem().toString() =="GBP"){
               total= amount; 
               JOptionPane.showMessageDialog(this,"Your amount will be: "+total.toString());

            }
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Please enter an amount");
        }
            

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
              // TODO add your handling code here:
              
              String aux=txtfrom.getSelectedItem().toString();
              txtfrom.setSelectedItem(txtto.getSelectedItem().toString());
              txtto.setSelectedItem(aux);
              
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
